import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/Login.vue'),
    meta: { titleKey: 'routes.login', public: true },
  },
  {
    path: '/welcome',
    name: 'Welcome',
    component: () => import('@/views/lingjing/Welcome.vue'),
    meta: { public: true, hidden: true },
  },
  {
    path: '/register',
    name: 'Register',
    component: () => import('@/views/lingjing/Register.vue'),
    meta: { public: true, hidden: true },
  },
  {
    path: '/',
    component: () => import('@/layouts/DefaultLayout.vue'),
    meta: { requiresAuth: true },
    children: [
      {
        path: '',
        redirect: { name: 'Chat' },
        meta: { hidden: true },
      },
      {
        path: 'dashboard',
        name: 'Dashboard',
        component: () => import('@/views/Dashboard.vue'),
        meta: { titleKey: 'routes.dashboard', icon: 'GridOutline', gateway: 'openclaw', hidden: true },
      },
      {
        path: 'chat',
        name: 'Chat',
        component: () => import('@/views/chat/ChatPage.vue'),
        meta: { title: '对话', icon: 'ChatboxEllipsesOutline', gateway: 'openclaw', section: 'use' },
      },
      {
        path: 'sessions',
        name: 'Sessions',
        component: () => import('@/views/sessions/SessionsPage.vue'),
        meta: { title: '历史', icon: 'ChatbubblesOutline', gateway: 'openclaw', section: 'use' },
      },
      {
        path: 'sessions/:key',
        name: 'SessionDetail',
        component: () => import('@/views/sessions/SessionDetailPage.vue'),
        meta: { titleKey: 'routes.sessionDetail', hidden: true },
      },
      {
        path: 'memory',
        name: 'Memory',
        component: () => import('@/views/memory/MemoryPage.vue'),
        meta: { titleKey: 'routes.memory', icon: 'BookOutline', gateway: 'openclaw', hidden: true },
      },
      {
        path: 'cron',
        name: 'Cron',
        component: () => import('@/views/lingjing/CronPage.vue'),
        meta: { title: '自动化任务', icon: 'CalendarOutline', gateway: 'openclaw', section: 'build' },
      },
      {
        path: 'models',
        name: 'Models',
        component: () => import('@/views/lingjing/ModelsPage.vue'),
        meta: { title: '模型管理', icon: 'SparklesOutline', gateway: 'openclaw', section: 'build' },
      },
      {
        path: 'channels',
        name: 'Channels',
        component: () => import('@/views/lingjing/ChannelsPage.vue'),
        meta: { title: '通信渠道', icon: 'GitNetworkOutline', gateway: 'openclaw', section: 'build' },
      },
      {
        path: 'config',
        redirect: { name: 'Models' },
        meta: { hidden: true },
      },
      {
        path: 'skills',
        name: 'Skills',
        component: () => import('@/views/lingjing/SkillsPage.vue'),
        meta: { title: '技能广场', icon: 'ExtensionPuzzleOutline', gateway: 'openclaw', section: 'build' },
      },
      {
        path: 'tools',
        redirect: { name: 'Skills' },
        meta: { hidden: true },
      },
      {
        path: 'system',
        name: 'System',
        component: () => import('@/views/system/SystemPage.vue'),
        meta: { titleKey: 'routes.system', icon: 'PulseOutline', gateway: 'openclaw', hidden: true },
      },
      {
        path: 'terminal',
        name: 'Terminal',
        component: () => import('@/views/terminal/TerminalPage.vue'),
        meta: { titleKey: 'routes.terminal', icon: 'TerminalOutline', gateway: 'openclaw', hidden: true },
      },
      {
        path: 'remote-desktop',
        name: 'RemoteDesktop',
        component: () => import('@/views/remote-desktop/RemoteDesktopPage.vue'),
        meta: { titleKey: 'routes.remoteDesktop', icon: 'DesktopOutline', gateway: 'openclaw', hidden: true },
      },
      {
        path: 'files',
        name: 'Files',
        component: () => import('@/views/files/FilesPage.vue'),
        meta: { titleKey: 'routes.files', icon: 'FolderOutline', gateway: 'openclaw', hidden: true },
      },
      {
        path: 'agents',
        name: 'Agents',
        component: () => import('@/views/lingjing/AgentsPage.vue'),
        meta: { title: '多智能体', icon: 'PeopleOutline', gateway: 'openclaw', section: 'build' },
      },
      {
        path: 'office',
        name: 'Office',
        component: () => import('@/views/office/OfficePage.vue'),
        meta: { titleKey: 'routes.office', icon: 'ConstructOutline', gateway: 'openclaw', hidden: true },
      },
      {
        path: 'myworld',
        name: 'MyWorld',
        component: () => import('@/views/lingjing/MyWorldPage.vue'),
        meta: { title: '虚拟公司', icon: 'BusinessOutline', gateway: 'openclaw', section: 'build' },
      },
      {
        path: 'backup',
        name: 'Backup',
        component: () => import('@/views/backup/BackupPage.vue'),
        meta: { titleKey: 'routes.backup', icon: 'ArchiveOutline', gateway: 'openclaw', hidden: true },
      },
      {
        path: 'monitor',
        name: 'Monitor',
        component: () => import('@/views/monitor/MonitorPage.vue'),
        meta: { titleKey: 'routes.monitor', icon: 'PulseOutline', hidden: true },
      },
      {
        path: 'hermes',
        name: 'HermesDashboard',
        component: () => import('@/views/hermes/HermesDashboard.vue'),
        meta: { titleKey: 'routes.hermesDashboard', icon: 'GridOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/chat',
        name: 'HermesChat',
        component: () => import('@/views/hermes/HermesChatPage.vue'),
        meta: { titleKey: 'routes.hermesChat', icon: 'ChatboxEllipsesOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/sessions',
        name: 'HermesSessions',
        component: () => import('@/views/hermes/HermesSessionsPage.vue'),
        meta: { titleKey: 'routes.hermesSessions', icon: 'ChatbubblesOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/models',
        name: 'HermesModels',
        component: () => import('@/views/hermes/HermesModelsPage.vue'),
        meta: { titleKey: 'routes.hermesModels', icon: 'SparklesOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/channels',
        name: 'HermesChannels',
        component: () => import('@/views/hermes/HermesChannelsPage.vue'),
        meta: { titleKey: 'routes.hermesChannels', icon: 'GitNetworkOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/skills',
        name: 'HermesSkills',
        component: () => import('@/views/hermes/HermesSkillsPage.vue'),
        meta: { titleKey: 'routes.hermesSkills', icon: 'ExtensionPuzzleOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/cron',
        name: 'HermesCron',
        component: () => import('@/views/hermes/HermesCronPage.vue'),
        meta: { titleKey: 'routes.hermesCron', icon: 'CalendarOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/memory',
        name: 'HermesMemory',
        component: () => import('@/views/hermes/HermesMemoryPage.vue'),
        meta: { titleKey: 'routes.hermesMemory', icon: 'BookOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/cli',
        name: 'HermesCli',
        component: () => import('@/views/hermes/HermesCliPage.vue'),
        meta: { titleKey: 'routes.hermesCli', icon: 'CodeSlashOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/terminal',
        name: 'HermesTerminal',
        component: () => import('@/views/hermes/HermesTerminalPage.vue'),
        meta: { titleKey: 'routes.hermesTerminal', icon: 'TerminalOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/remote-desktop',
        name: 'HermesRemoteDesktop',
        component: () => import('@/views/hermes/HermesRemoteDesktopPage.vue'),
        meta: { titleKey: 'routes.hermesRemoteDesktop', icon: 'DesktopOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/files',
        name: 'HermesFiles',
        component: () => import('@/views/hermes/HermesFilesPage.vue'),
        meta: { titleKey: 'routes.hermesFiles', icon: 'FolderOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'hermes/system',
        name: 'HermesSystem',
        component: () => import('@/views/hermes/HermesSystemPage.vue'),
        meta: { titleKey: 'routes.hermesSystem', icon: 'SettingsOutline', gateway: 'hermes', hidden: true },
      },
      {
        path: 'settings',
        name: 'Settings',
        component: () => import('@/views/lingjing/SettingsPage.vue'),
        meta: { title: '系统设置', icon: 'CogOutline', gateway: 'openclaw', section: 'system' },
      },
    ],
  },
]
